export const AppLinks=[
    {text:'LLP Registration',li:'LlpRegistration'},
    {text:'One person Company Registration',li:'OnePersonCompanyRegistration'},
    {text:'Pvt Ltd Company Registration',li:'PvtLtdRegistration'},
    {text:'Ltd Company Registration',li:'LtdCompanyRegistration'},
    {text:'Partnership Firm Registration',li:'PartnershipFirmRegistration'},
    {text:'EPF Registration',li:'EPFRegistration'},
    {text:'ESI Registration',li:'ESIRegistration'},
    {text:'Trademark Registration',li:'TrademarkRegistration'},
    {text:'Trademark Renewal',li:'TrademarkRenewal'},
    {text:'Trademark Objection reply',li:'TrademarkObjectionReply'},
    {text:'Trademark Rectification',li:'TrademarkRectification'},
    {text:'Trademark Objection',li:'TrademarkObjection'},
    {text:'Trademark opposition',li:'TrademarkOpposition'},
    {text:'Trademark counter Statement',li:'TrademarkCounterStatement'},
    {text:'Trademark Cancellation',li:'TrademarkCancellation'},
    {text:'Trademark-NOC',li:'Trademark-NOC'},
    {text:'Trademark security Services',li:'TrademarkSecurityServices'},
    {text:'Trademark Hearing Services',li:'TrademarkHearingServices'},
    {text:'Copyright Registration',li:'CopyrightRegistration'},
    {text:'Design Registration',li:'Design Registration'},
    {text:'Fssai Registration',li:'FssaiRegistration'},
    {text:'Fssai License',li:'FssaiLicense'},
    {text:'Import Export code',li:'ImportExportCode'},
    {text:'Trust Registration',li:'TrustRegistration'},
    {text:'Udyam Registration',li:'UdyamRegistration'},
    {text:'Psra License',li:'PsraLicense'},
    {text:'ITR Filing',li:'ITRFiling'},
    {text:'GST Registration',li:'GSTRegistration'},
    {text:'GST Filing',li:'GSTFiling'},
    {text:'TDS Filing',li:'TDSFiling'},
    {text:'ROC Filing',li:'ROCFiling'},
    {text:'Legal services',li:'LegalServices'}
];